version: '3.8'
services:
  api:
    container_name: api
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/server

  db:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - ./pgdata:/var/lib/postgresql/data #persistindo dados para quando derrubar container não apagar os arquivos.
    environment:
      - POSTGRES_USER:=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'

volumes:
  data: {}
